- name: To setup backend component of Expense Shell Project
  hosts: backend
  become: yes
  tasks:
    - name: To disable default nodejs module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: To disable default nodejs:18 module
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: To install nodejs version 18
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: To copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: To create Expense user
      ansible.builtin.user:
        name: expense

    - name: To remove old app content directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: To remove old app content directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: To download and extract backend app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Download NodeJS Dependencies
      ansible.builtin.shell: npm install

    - name: To install mysql client to old app schema
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: To old app schema
      ansible.builtin.shell: mysql -h mysql-dev.rdevopsb72.online -uroot -p"{{ MYSQL_ROOT_PASSWORD }}" < /app/schema/backend.sql

    - name: To start nodejs services
      ansible.builtin.systemd_service:
        state: restarted
        name: nodejs
        enabled: true
        daemon_reload: true