- name: To disable default nodejs module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: To disable default nodejs:18 module
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: To install nodejs version 18
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: To copy backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: To create Expense user
  ansible.builtin.user:
    name: expense

- name: Import common role App prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq
  vars:
    app_dir: /app
    component: backend

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: To install mysql client to old app schema
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: To old app schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_HOST', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql

- name: To start nodejs services
  ansible.builtin.systemd_service:
    state: restarted
    name: backend
    enabled: true
    daemon_reload: true

- name: To import elk role to install filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

