- name: To install nginx web server package
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: To copy expense configuration file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import common role App prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq
  vars:
    app_dir: /usr/share/nginx/html
    component: frontend

#- name: Run tasks/other.yaml instead of 'main'
#ansible.builtin.import_role:
#  name: myrole
#  tasks_from: other

- name: To start Nginx services
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true