- name: To copy rsyslog configuration
  ansible.builtin.template:
    src: {{ component }}.conf
    dest: /etc/rsyslog.d/{{ component }}.conf
  when: is_rsyslog_needed

- name: To restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
  when: is_rsyslog_needed

- name: To copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install file beat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: To copy file beat configration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: To restart filebeat
  ansible.builtin.systemd_service:
    name: filebeat
    state: restarted
    enabled: true