- name: To copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install file beat
  anisble.builtin.dnf:
    name: filebeat
    state: installed